apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kantyna-orders-api
  namespace: robert
  labels:
    app.kubernetes.io/part-of: kantyna
    aiops/lab: lab04
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orders-api
      app.kubernetes.io/instance: kantyna
